name: Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-docker-username/simple-java-app:$GITHUB_SHA .

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: docker tag your-docker-username/simple-java-app:$GITHUB_SHA your-docker-username/simple-java-app:latest

      - name: Push Docker image to Docker Hub
        run: docker push your-docker-username/simple-java-app
